# Generated by Django 4.0 on 2024-05-17 10:46

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('cmnt_id', models.IntegerField(default=blog.models.generate_comment_id, primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=500)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
        ),
    ]
